version: '3.8'

services:
  deeplx-transform:
    build: .
    container_name: deeplx-transform
    ports:
      - "8080:8080"  # 主机端口:容器端口
    environment:
      # Gin 框架模式
      - GIN_MODE=release  # 可选: debug, release, test
      
      # 覆盖目标服务配置（可选）
      # - TARGET_BASE_URL=https://api.deeplx.org
      
      # 其他环境变量（根据需要添加）
      # - HTTP_PROXY=http://proxy.example.com:8080
      # - HTTPS_PROXY=http://proxy.example.com:8080
      
    volumes:
      # 挂载配置文件（必需）
      - ./config.yaml:/root/config.yaml
      
      # 如果需要持久化日志（可选）
      # - ./logs:/root/logs
      
    restart: unless-stopped  # 自动重启策略
    
    # 资源限制（可选）
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    
    # 健康检查
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    
    # 日志配置
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"